### ISSUE TITLE
Textual Doesn't Work

### ISSUE THREAD

**Issue by https123456789** [https123456789/Textual#13]
# Textual Doesn't Work.

When I download the projecta and run it, Textual does not work. Technically, Textual run and is still a viable text editor, but the page does not load the theme and so the page remains blank.

## Screen Shots

![Screenshot 2021-11-03 16 05 38](https://user-images.githubusercontent.com/81256789/140230829-7028b84c-39a3-4ab8-8b70-3448d0c15da1.png)
![Screenshot 2021-11-03 16 05 27](https://user-images.githubusercontent.com/81256789/140230831-e4e6a638-c9af-457d-aaf7-dfcedde25d65.png)

**Comment by LGgameLAB** [comment]
you want me to fix?

**Comment by https123456789** [comment]
If you know you can fix it then sure. I have an idea that might work, but I am not certain.
